# Generated by Django 5.2.9 on 2025-12-26 22:28

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('funcao', models.CharField(max_length=200)),
                ('empresa', models.CharField(choices=[('M', 'Matriz'), ('A', 'Filial Argentina'), ('E', 'Filial Estados Unidos')], default='M', max_length=1)),
                ('flag_ativo', models.BooleanField(default=1)),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateField(default=datetime.datetime, editable=False)),
                ('update_at', models.DateField(null=True)),
            ],
        ),
    ]
