# Generated by Django 5.2.9 on 2025-12-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
